; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DBOARD_HAS_PSRAM

lib_deps =
    alvarowolfx/ESP32QRCodeReader
    marcoschwartz/LiquidCrystal_I2C
    https://github.com/0015/ESP32-OV5640-AF.git

; If esp_camera.h is not found on your setup, uncomment this:
; lib_deps =
;   espressif/esp32-camera